library(ioregression)
library(testthat)

data = read.csv("http://www.ats.ucla.edu/stat/data/binary.csv")
form = admit ~ gre + gpa + rank
glmfit = glm(form, data=data, family = binomial())
iofit = ioglm(form, data = data, family = binomial())

expect_equal(iofit$coefficients, glmfit$coefficients)
expect_equal(iofit$rank, glmfit$rank)
expect_equal(iofit$family, glmfit$family)
expect_equal(iofit$deviance, glmfit$deviance)
expect_equal(iofit$aic, glmfit$aic)
expect_equal(iofit$iter, glmfit$iter+1)
expect_equal(iofit$converged, glmfit$converged)
expect_equal(iofit$formula, glmfit$formula)
expect_equal(iofit$terms, glmfit$terms)
expect_equal(iofit$contrasts, glmfit$contrasts)

sg = summary(glmfit)
s = summary(iofit)

expect_equal(s$terms, sg$terms)
expect_equal(s$family, sg$family)
expect_equal(s$deviance, sg$deviance)
expect_equal(s$aic, sg$aic)
expect_equal(s$contrasts, sg$contrasts)
expect_equal(s$df.residual, sg$df.residual)
expect_equal(s$null.deviance, sg$null.deviance)
expect_equal(s$df.null, sg$df.null)
expect_equal(s$coefficients, sg$coefficients)
expect_equal(s$dispersion, sg$dispersion)
expect_equal(s$df, sg$df)
expect_equal(s$cov.unscaled, sg$cov.unscaled, tol=0.001)
expect_equal(s$cov.scaled, sg$cov.scaled, tol=0.001)

